### ISSUE TITLE
Stream-based API is difficult to use due to buffer lifetime

### ISSUE THREAD

**Issue by hannobraun** [inotify-rs/inotify#120]
See https://github.com/inotify-rs/inotify/issues/106#issuecomment-418343576.

#119 adds an example for working around this issue.

**Comment by hannobraun** [comment]
I don't think I'll have time to work on this very soon. I'll take a look eventually, but in the meantime, any help is appreciated.

**Comment by hawkw** [comment]
I have a potential solution for this, but it'll require another API change. Happy to open a PR if you're interested.

**Comment by hannobraun** [comment]
@hawkw 
> I have a potential solution for this, but it'll require another API change. Happy to open a PR if you're interested.

Thank you, I'm always interested in fixing problems. Breaking compatibility is a downside, of course, but I think it's unreasonable to rule that out while the API is having problems like this.

**Comment by hawkw** [comment]
@hannobraun I've opened #124 to resolve this issue --- please let me know what you think! It works quite well [in my use-case](https://github.com/linkerd/linkerd2-proxy/pull/170/commits/79eca8a4e9ef19eb61c27c685f17575ef36e034f) but do let me know if I've overlooked something.
