### ISSUE TITLE
Look into automatic changelog generation

### ISSUE THREAD

**Issue by hannobraun** [inotify-rs/inotify#48]
I've heard of projects, for example [Hyper](http://hyper.rs), automatically generating changelogs from Git commits. I haven't looked into the details yet, but I understand that [GitCop](https://gitcop.com/) can be used to enforce the commit message format that's required for that.

**Comment by hannobraun** [comment]
I've done some additional research. There a [document in the Hyper repository](https://github.com/hyperium/hyper/blob/1ee26443f4553ad8155125b4d1a5f267f5af6c78/CONTRIBUTING.md) that details the commit guidelines and mentions they generate the changelog automatically.

They don't mention which tool they use for doing that, but I've found the following on [crates.io](https://crates.io/):
- [clog](https://crates.io/crates/clog)/[clog-cli](https://crates.io/crates/clog-cli)
- [git-journal](https://crates.io/crates/git-journal)
- [changelog-rs](https://crates.io/crates/changelog-rs)

**Comment by arsalan86** [comment]
[Gitcop](www.gitcop.com) seems like a useful tool to enforce guidelines. I haven't used it yet myself, but I think it's worth considering for this use case.

**Comment by hannobraun** [comment]
I've done further research. So far [clog](https://crates.io/crates/clog-cli) stands out, as I like both the changelogs it generates and the style of commit message it mandates. However, I don't think any of the tools can handle multi-crate repositories.

While it should be possible to add support for that feature, I wonder if it wouldn't be better to just create another separate repository for inotify-sys. If we were doing that, it may be good to move both repositories to a dedicated GitHub organization. That way, anyone who finds one of the repositories could quickly find all related ones. This would not be the case, if they were under my personal GitHub account.

I'll take some time to think this over.

**Comment by hannobraun** [comment]
I've decided to go ahead on this. I've created an organization and will move the repository shortly. After that, I'll move inotify-sys into a separate repository under that organization.

**Comment by hannobraun** [comment]
The repository has been moved to an organization and inotify-sys now lives in its own repository. Next up is setting up GitCop.

**Comment by hannobraun** [comment]
Everything's ready now. For the release after the next one, we should have enough formatted commits to generate a changelog. I'm going to leave this issue open until then, as a reminder.

**Comment by hannobraun** [comment]
This has been done for a while, and the last release already included an auto-generated changelog.
